name: Tests
on:
    pull_request:
    push:
        branches:
            - main
            - dev
            - release/**

jobs:
    cleanup-runs:
        runs-on: ubuntu-latest
        steps:
            - uses: rokroskar/workflow-run-cleanup-action@master
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

    run-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v4.1.0
              with:
                  go-version: 1.21
                  check-latest: true
            - uses: actions/checkout@v3
            - uses: technote-space/get-diff-action@v6.1.2
              with:
                  PATTERNS: |
                      **/**.go
                      go.mod
                      go.sum
            - name: Test
              run: |
                  make test
              if: env.GIT_DIFF
